"""Download and convert a NIST SP 800-53 OSCAL catalog for SRG ingest."""

from __future__ import annotations

import hashlib
import json
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlparse
from urllib.request import Request, urlopen

DEFAULT_NIST_OSCAL_URL = (
    "https://raw.githubusercontent.com/usnistgov/oscal-content/v1.4.0/"
    "nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json"
)

_MAX_DOWNLOAD_BYTES = 50 * 1024 * 1024
_PARAM_INSERT_RE = re.compile(r"\{\{\s*insert:\s*param,\s*([^}\s]+)\s*\}\}")
_HEADING_UNSUPPORTED_RE = re.compile(r"[^A-Z0-9,'/&()| -]+")


class CatalogError(ValueError):
    """Raised when an OSCAL source cannot be safely converted."""


@dataclass(frozen=True)
class ConversionResult:
    markdown: str
    version: str
    control_count: int
    enhancement_count: int
    source_sha256: str


def load_oscal_source(source: str) -> bytes:
    """Load OSCAL JSON from an HTTPS URL or local path."""
    parsed = urlparse(source)
    if parsed.scheme:
        if parsed.scheme != "https":
            raise CatalogError("Remote OSCAL sources must use HTTPS.")
        request = Request(source, headers={"User-Agent": "security-response-generator"})
        try:
            with urlopen(request, timeout=60) as response:
                final_url = response.geturl()
                if urlparse(final_url).scheme != "https":
                    raise CatalogError("The OSCAL download redirected to a non-HTTPS URL.")
                content_length = response.headers.get("Content-Length")
                if content_length and int(content_length) > _MAX_DOWNLOAD_BYTES:
                    raise CatalogError("The OSCAL download exceeds the 50 MiB safety limit.")
                payload = response.read(_MAX_DOWNLOAD_BYTES + 1)
        except CatalogError:
            raise
        except Exception as exc:
            raise CatalogError(f"Unable to download the OSCAL catalog: {exc}") from exc
        if len(payload) > _MAX_DOWNLOAD_BYTES:
            raise CatalogError("The OSCAL download exceeds the 50 MiB safety limit.")
        return payload

    path = Path(source).expanduser()
    try:
        if path.stat().st_size > _MAX_DOWNLOAD_BYTES:
            raise CatalogError("The OSCAL file exceeds the 50 MiB safety limit.")
        return path.read_bytes()
    except CatalogError:
        raise
    except OSError as exc:
        raise CatalogError(f"Unable to read the OSCAL catalog: {exc}") from exc


def convert_oscal_catalog(payload: bytes, source: str) -> ConversionResult:
    """Validate an OSCAL catalog and render its SP 800-53 content as Markdown."""
    try:
        document = json.loads(payload)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise CatalogError(f"The OSCAL source is not valid UTF-8 JSON: {exc}") from exc

    catalog = document.get("catalog") if isinstance(document, dict) else None
    if not isinstance(catalog, dict):
        raise CatalogError("The OSCAL JSON does not contain a catalog object.")

    metadata = catalog.get("metadata")
    groups = catalog.get("groups")
    if not isinstance(metadata, dict) or not isinstance(groups, list):
        raise CatalogError("The OSCAL catalog is missing metadata or control groups.")

    title = metadata.get("title")
    version = metadata.get("version")
    last_modified = metadata.get("last-modified")
    if not isinstance(title, str) or "800-53" not in title:
        raise CatalogError("The OSCAL catalog is not identified as NIST SP 800-53.")
    if not isinstance(version, str) or not version.strip():
        raise CatalogError("The OSCAL catalog metadata does not contain a version.")

    source_sha256 = hashlib.sha256(payload).hexdigest()
    lines = [
        "NIST SP 800-53 CONTROL CATALOG",
        "",
        "Generated by Security Response Generator from a NIST OSCAL catalog.",
        f"Catalog title: {_single_line(title)}",
        f"Catalog version: {_single_line(version)}",
    ]
    if isinstance(last_modified, str) and last_modified:
        lines.append(f"Catalog last modified: {_single_line(last_modified)}")
    lines.extend(
        [
            f"Source: {_single_line(source)}",
            f"Source SHA-256: {source_sha256}",
            (
                "Content scope: SP 800-53 control statements, organization-defined "
                "parameters, guidance, and related-control references. SP 800-53A "
                "assessment objectives and methods are intentionally excluded."
            ),
            "",
        ]
    )

    control_count = 0
    enhancement_count = 0
    for group in groups:
        if not isinstance(group, dict):
            continue
        controls = group.get("controls", [])
        if not isinstance(controls, list):
            continue
        for control in controls:
            if not _is_control(control):
                continue
            control_count += 1
            lines.extend(_render_control(control))
            enhancements = control.get("controls", [])
            if not isinstance(enhancements, list):
                continue
            for enhancement in enhancements:
                if not _is_control(enhancement):
                    continue
                enhancement_count += 1
                lines.extend(_render_control(enhancement, parent_id=control["id"]))

    if control_count == 0:
        raise CatalogError("The OSCAL catalog contains no SP 800-53 controls.")

    return ConversionResult(
        markdown="\n".join(lines).rstrip() + "\n",
        version=version,
        control_count=control_count,
        enhancement_count=enhancement_count,
        source_sha256=source_sha256,
    )


def write_catalog_markdown(output: Path, markdown: str) -> None:
    """Atomically write converted catalog Markdown."""
    output = output.expanduser()
    temporary_path: Path | None = None
    try:
        output.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output.parent,
            prefix=f".{output.name}.",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary.write(markdown)
            temporary_path = Path(temporary.name)
        temporary_path.replace(output)
    except OSError as exc:
        raise CatalogError(f"Unable to write the converted catalog: {exc}") from exc
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def update_catalog(source: str, output: Path) -> ConversionResult:
    """Load, convert, and write a NIST OSCAL catalog."""
    payload = load_oscal_source(source)
    result = convert_oscal_catalog(payload, source)
    write_catalog_markdown(output, result.markdown)
    return result


def _is_control(value: Any) -> bool:
    return (
        isinstance(value, dict)
        and isinstance(value.get("id"), str)
        and isinstance(value.get("title"), str)
    )


def _render_control(control: dict[str, Any], parent_id: str | None = None) -> list[str]:
    oscal_id = control["id"]
    control_id = _display_control_id(oscal_id)
    title = _heading_title(control["title"])
    if parent_id is None:
        heading = f"{control_id} {title}"
    else:
        enhancement_number = _enhancement_number(oscal_id, parent_id)
        heading = f"({enhancement_number}) {title}"

    lines = [heading, "", f"Control ID: {control_id}", ""]
    status = _property_value(control, "status")
    if status:
        lines.extend([f"Status: {status.title()}", ""])

    parameters = control.get("params", [])
    parameter_map = {
        parameter["id"]: parameter
        for parameter in parameters
        if isinstance(parameter, dict) and isinstance(parameter.get("id"), str)
    }

    statement_parts = _parts_named(control, "statement")
    if statement_parts:
        lines.extend(["Control:", ""])
        for part in statement_parts:
            lines.extend(_render_part(part, parameter_map))

    if parameter_map:
        lines.extend(["Organization-Defined Parameters:", ""])
        for parameter in parameter_map.values():
            lines.append(f"- {_parameter_definition(parameter, parameter_map)}")
        lines.append("")

    guidance_parts = _parts_named(control, "guidance")
    if guidance_parts:
        lines.extend(["Discussion:", ""])
        for part in guidance_parts:
            lines.extend(_render_part(part, parameter_map))

    related = _linked_control_ids(control, "related")
    if related:
        lines.extend([f"Related Controls: {', '.join(related)}", ""])

    incorporated = _linked_control_ids(control, "incorporated-into")
    if incorporated:
        lines.extend([f"Incorporated Into: {', '.join(incorporated)}", ""])

    return lines


def _parts_named(control: dict[str, Any], name: str) -> list[dict[str, Any]]:
    parts = control.get("parts", [])
    if not isinstance(parts, list):
        return []
    return [part for part in parts if isinstance(part, dict) and part.get("name") == name]


def _render_part(part: dict[str, Any], parameter_map: dict[str, dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    prose = part.get("prose")
    label = _property_value(part, "label")
    if isinstance(prose, str) and prose.strip():
        resolved = _resolve_parameter_inserts(prose.strip(), parameter_map)
        lines.extend([f"{label} {resolved}" if label else resolved, ""])

    children = part.get("parts", [])
    if isinstance(children, list):
        for child in children:
            if isinstance(child, dict):
                lines.extend(_render_part(child, parameter_map))
    return lines


def _parameter_definition(
    parameter: dict[str, Any],
    parameter_map: dict[str, dict[str, Any]],
) -> str:
    property_label = _property_value(parameter, "label")
    description = parameter.get("label")
    identifier = (
        property_label
        or (description.strip() if isinstance(description, str) and description.strip() else None)
        or parameter["id"]
    )
    selection = parameter.get("select")
    details: list[str] = []
    if isinstance(description, str) and description.strip() and description.strip() != identifier:
        details.append(description.strip())
    if isinstance(selection, dict):
        choices = selection.get("choice", [])
        if isinstance(choices, list):
            resolved_choices = [
                _resolve_parameter_inserts(str(choice).strip(), parameter_map)
                for choice in choices
                if str(choice).strip()
            ]
            if resolved_choices:
                how_many = selection.get("how-many")
                selection_label = (
                    f"select {how_many}" if isinstance(how_many, str) else "select one"
                )
                details.append(f"{selection_label}: {'; '.join(resolved_choices)}")
    guidelines = parameter.get("guidelines", [])
    if isinstance(guidelines, list):
        for guideline in guidelines:
            if isinstance(guideline, dict) and isinstance(guideline.get("prose"), str):
                details.append(
                    _resolve_parameter_inserts(guideline["prose"].strip(), parameter_map)
                )
    return f"{identifier}: {'; '.join(details)}" if details else identifier


def _resolve_parameter_inserts(
    prose: str,
    parameter_map: dict[str, dict[str, Any]],
    resolving: frozenset[str] = frozenset(),
) -> str:
    def replace(match: re.Match[str]) -> str:
        parameter_id = match.group(1)
        if parameter_id in resolving:
            return f"[Organization-defined parameter: {parameter_id}]"
        parameter = parameter_map.get(parameter_id)
        if parameter is None:
            return f"[Organization-defined parameter: {parameter_id}]"

        label = parameter.get("label")
        selection = parameter.get("select")
        if isinstance(selection, dict):
            choices = selection.get("choice", [])
            if isinstance(choices, list):
                resolved = [
                    _resolve_parameter_inserts(
                        str(choice).strip(),
                        parameter_map,
                        resolving | {parameter_id},
                    )
                    for choice in choices
                    if str(choice).strip()
                ]
                if resolved:
                    how_many = selection.get("how-many")
                    qualifier = f", {how_many}" if isinstance(how_many, str) else ""
                    return f"[Organization-defined selection{qualifier}: {'; '.join(resolved)}]"
        if isinstance(label, str) and label.strip():
            return f"[Organization-defined parameter: {label.strip()}]"
        return f"[Organization-defined parameter: {parameter_id}]"

    return _PARAM_INSERT_RE.sub(replace, prose)


def _property_value(item: dict[str, Any], name: str) -> str | None:
    properties = item.get("props", [])
    if not isinstance(properties, list):
        return None
    for prop in properties:
        if not isinstance(prop, dict) or prop.get("name") != name:
            continue
        value = prop.get("value")
        if isinstance(value, str) and value:
            return value
    return None


def _linked_control_ids(control: dict[str, Any], relation: str) -> list[str]:
    links = control.get("links", [])
    if not isinstance(links, list):
        return []
    values = []
    for link in links:
        if not isinstance(link, dict) or link.get("rel") != relation:
            continue
        href = link.get("href")
        if isinstance(href, str) and href.startswith("#"):
            linked_id = href[1:]
            if re.fullmatch(r"[a-z]{2}-\d+(?:\.\d+)?", linked_id):
                values.append(_display_control_id(linked_id))
    return values


def _display_control_id(oscal_id: str) -> str:
    match = re.fullmatch(r"([a-zA-Z]{2})-(\d+)(?:\.(\d+))?", oscal_id)
    if not match:
        raise CatalogError(f"Unsupported OSCAL control identifier: {oscal_id}")
    family, number, enhancement = match.groups()
    base = f"{family.upper()}-{int(number)}"
    return f"{base}({int(enhancement)})" if enhancement is not None else base


def _enhancement_number(oscal_id: str, parent_id: str) -> int:
    display_id = _display_control_id(oscal_id)
    display_parent = _display_control_id(parent_id)
    match = re.fullmatch(rf"{re.escape(display_parent)}\((\d+)\)", display_id)
    if not match:
        raise CatalogError(
            f"Enhancement {oscal_id} is not a child of its declared parent {parent_id}."
        )
    return int(match.group(1))


def _heading_title(title: str) -> str:
    normalized = title.upper().replace("—", "-").replace("–", "-")
    normalized = _HEADING_UNSUPPORTED_RE.sub(" ", normalized)
    normalized = re.sub(r"\s+", " ", normalized).strip(" -")
    return normalized or "CONTROL"


def _single_line(value: str) -> str:
    return " ".join(value.split())
